'use client';

import { useEffect, useMemo, useRef, useState } from 'react';
import { useQuery } from '@tanstack/react-query';
import { Drawer } from 'vaul';
import { SlidersHorizontal, X } from 'lucide-react';
import { usePathname, useRouter, useSearchParams } from 'next/navigation';
import type { SportSlug, VenueCard as Venue } from '@rally/shared';
import { api } from '@/lib/api-client';
import dynamicImport from 'next/dynamic';
import { VenueCard } from '@/components/venue/venue-card';
import { VenueCardSkeleton } from '@/components/shared/loading-skeleton';
import { EmptyState } from '@/components/shared/empty-state';

const sports: SportSlug[] = ['basketball', 'pickleball', 'tennis', 'soccer', 'volleyball', 'baseball', 'softball', 'running_track', 'golf_range', 'skate', 'football', 'handball'];
const MapCanvas = dynamicImport(() => import('@/components/map/map-canvas').then((module) => module.MapCanvas), { ssr: false, loading: () => <div className="h-full w-full animate-pulse bg-rally-elevated" aria-label="Loading map" /> });
const chicago = { lat: 41.8781, lng: -87.6298 };
type Filters = { indoor: boolean; free: boolean; lights: boolean };

export default function MapHome() {
  const router = useRouter(); const pathname = usePathname(); const params = useSearchParams();
  const sport = (params.get('sport') as SportSlug | null) ?? 'basketball'; const radius = Number(params.get('radius') ?? 5); const playable = params.get('playableNow') === 'true';
  const filters = { indoor: params.get('indoor') === 'true', free: params.get('free') === 'true', lights: params.get('lights') === 'true' };
  const [position, setPosition] = useState(chicago); const [usingHome, setUsingHome] = useState(false); const [selected, setSelected] = useState<string>(); const [filterOpen, setFilterOpen] = useState(false); const [snap, setSnap] = useState<number | string | null>(0.12); const cardRefs = useRef<Record<string, HTMLDivElement | null>>({});
  const setState = (patch: Record<string, string | boolean | number | null>) => { const next = new URLSearchParams(params.toString()); Object.entries(patch).forEach(([key, value]) => value === false || value === null ? next.delete(key) : next.set(key, String(value))); router.replace(`${pathname}?${next.toString()}`, { scroll: false }); };
  useEffect(() => { if (!navigator.geolocation) { setUsingHome(true); return; } navigator.geolocation.getCurrentPosition(({ coords }) => setPosition({ lat: coords.latitude, lng: coords.longitude }), () => setUsingHome(true), { timeout: 5000, maximumAge: 300_000 }); }, []);
  const query = useQuery({ queryKey: ['recommended', sport, radius, playable, filters, position], queryFn: () => api.get<{ items: Venue[] }>(`/feed/recommended?lat=${position.lat}&lng=${position.lng}&sport=${sport}&radius=${radius * 1000}&playableNow=${playable}&indoor=${filters.indoor}&free=${filters.free}&hasLights=${filters.lights}`), staleTime: 30_000, refetchInterval: playable ? 60_000 : false, refetchOnWindowFocus: true });
  const venues = useMemo(() => (query.data?.items ?? []).filter((venue) => !playable || Boolean(venue.live?.activeCount)).sort((a, b) => (b.reco?.rallyScore ?? 0) - (a.reco?.rallyScore ?? 0)), [playable, query.data]);
  const chooseVenue = (venue: Venue) => { setSelected(venue.id); setSnap(0.55); requestAnimationFrame(() => cardRefs.current[venue.id]?.scrollIntoView({ behavior: 'smooth', block: 'nearest' })); };
  const activeFilters = Number(filters.indoor) + Number(filters.free) + Number(filters.lights);
  const list = query.isError ? <EmptyState icon="!" headline="Couldn’t load nearby courts" body={query.error instanceof Error ? query.error.message : 'Try again in a moment.'} /> : <VenueList venues={venues} loading={query.isLoading} selected={selected} onSelect={chooseVenue} cardRefs={cardRefs} onWiden={() => setState({ radius: 15 })} />;
  return <main className="h-dvh overflow-hidden bg-rally-base lg:grid lg:grid-cols-[minmax(0,1fr)_440px]"><section className="relative min-h-0"><MapCanvas venues={venues} selected={selected} onSelect={chooseVenue} center={position} /><TopBar sport={sport} setSport={(value) => setState({ sport: value })} playable={playable} setPlayable={(value) => setState({ playableNow: value })} liveCount={venues.filter((venue) => venue.live?.activeCount).length} activeFilters={activeFilters} onFilters={() => setFilterOpen(true)} />{usingHome ? <p className="absolute bottom-4 left-4 rounded-control border border-rally-border bg-rally-surface/95 px-3 py-2 text-xs text-rally-secondary lg:bottom-auto lg:top-16">Using your home area</p> : null}</section><aside className="hidden min-h-0 overflow-y-auto border-l border-rally-border bg-rally-base p-3 lg:block">{list}</aside><Drawer.Root open={filterOpen} onOpenChange={setFilterOpen}><Drawer.Portal><Drawer.Overlay className="fixed inset-0 z-40 bg-black/55" /><Drawer.Content className="fixed inset-x-0 bottom-0 z-50 rounded-t-card border border-rally-border bg-rally-surface p-5"><FilterSheet radius={radius} filters={filters} setState={setState} onClose={() => setFilterOpen(false)} /></Drawer.Content></Drawer.Portal></Drawer.Root><Drawer.Root modal={false} snapPoints={[0.12, 0.55, 0.92]} activeSnapPoint={snap} setActiveSnapPoint={setSnap}><Drawer.Portal><Drawer.Content className="fixed inset-x-0 bottom-0 z-30 h-[92dvh] rounded-t-card border border-rally-border bg-rally-base outline-none lg:hidden"><div className="mx-auto my-3 h-1.5 w-12 rounded-full bg-rally-tertiary" /><div className="h-[calc(100%-36px)] overflow-y-auto px-3 pb-5">{list}</div></Drawer.Content></Drawer.Portal></Drawer.Root></main>;
}

function TopBar({ sport, setSport, playable, setPlayable, liveCount, activeFilters, onFilters }: { sport: SportSlug; setSport: (value: SportSlug) => void; playable: boolean; setPlayable: (value: boolean) => void; liveCount: number; activeFilters: number; onFilters: () => void }) { return <div className="absolute inset-x-3 top-3 z-20 flex gap-2"><div className="flex min-w-0 flex-1 gap-2 overflow-x-auto rounded-control border border-rally-border bg-rally-base/90 p-1 backdrop-blur"><button onClick={() => setPlayable(!playable)} className={`shrink-0 rounded-control px-3 py-2 text-sm font-medium ${playable ? 'bg-emerald-400 text-black' : 'bg-rally-surface'}`}>Playable now{playable ? ` · ${liveCount} courts live` : ''}</button>{sports.map((item) => <button key={item} onClick={() => setSport(item)} className={`shrink-0 rounded-control px-3 py-2 text-sm capitalize ${sport === item ? 'bg-rally-elevated text-rally-primary' : 'text-rally-secondary'}`}>{item.replace('_', ' ')}</button>)}</div><button aria-label="Open filters" onClick={onFilters} className="relative grid size-11 shrink-0 place-items-center rounded-control border border-rally-border bg-rally-surface"><SlidersHorizontal size={17} />{activeFilters ? <span className="absolute -right-1 -top-1 grid size-5 place-items-center rounded-full bg-emerald-400 text-xs text-black">{activeFilters}</span> : null}</button></div>; }
function FilterSheet({ radius, filters, setState, onClose }: { radius: number; filters: Filters; setState: (patch: Record<string, string | boolean | number | null>) => void; onClose: () => void }) { return <div className="mx-auto max-w-md"><div className="mb-5 flex items-center justify-between"><Drawer.Title className="text-lg font-semibold">Filters</Drawer.Title><button onClick={onClose} className="grid size-10 place-items-center rounded-control"><X size={18} /></button></div><label className="block text-sm">Radius <span className="float-right tabular-nums text-rally-secondary">{radius} km</span><input className="mt-3 w-full accent-emerald-400" type="range" min="1" max="15" value={radius} onChange={(event) => setState({ radius: Number(event.target.value) })} /></label><div className="mt-6 grid grid-cols-3 gap-2">{([['indoor', 'Indoor'], ['free', 'Free'], ['lights', 'Has lights']] as const).map(([key, label]) => <button key={key} onClick={() => setState({ [key]: !filters[key] })} className={`min-h-11 rounded-control border px-3 text-sm ${filters[key] ? 'border-emerald-400 bg-emerald-400/15' : 'border-rally-border bg-rally-elevated'}`}>{label}</button>)}</div><button onClick={() => setState({ radius: 5, indoor: null, free: null, lights: null })} className="mt-6 min-h-11 text-sm text-rally-secondary underline">Reset filters</button></div>; }
function VenueList({ venues, loading, selected, onSelect, cardRefs, onWiden }: { venues: Venue[]; loading: boolean; selected?: string; onSelect: (venue: Venue) => void; cardRefs: React.MutableRefObject<Record<string, HTMLDivElement | null>>; onWiden: () => void }) { if (loading) return <div className="space-y-2">{[1, 2, 3, 4].map((id) => <VenueCardSkeleton key={id} />)}</div>; if (!venues.length) return <EmptyState icon="⌁" headline="No courts nearby" body="Try widening the radius or clearing a filter." cta={<button onClick={onWiden} className="rounded-control bg-rally-elevated px-3 py-2 text-sm">Widen the radius</button>} />; return <div className="space-y-2">{venues.map((venue) => <div key={venue.id} ref={(node) => { cardRefs.current[venue.id] = node; }}><VenueCard venue={venue} selected={venue.id === selected} onSelect={() => onSelect(venue)} selectOnly /></div>)}</div>; }
