import { Router, type Router as RouterType } from 'express';
import { prisma } from '@rally/db';
import { requireAuth, optionalAuth } from '../middleware/auth.js';
import { asyncHandler, conflict, forbidden, notFound } from '../middleware/error.js';
import { CreateCheckInBody, FollowBody, WantToTryBody } from '@rally/shared';
import { validate } from '../middleware/validate.js';

const router: RouterType = Router();
const mini = (user: { id: string; handle: string; displayName: string; avatarUrl: string | null }) => ({ ...user });
const routeParam = (value: string | string[]) => Array.isArray(value) ? value[0] : value;

router.post('/check-ins', requireAuth, validate({ body: CreateCheckInBody }), asyncHandler(async (req, res) => { const body = req.body as typeof CreateCheckInBody._output; const sport = await prisma.sport.findUniqueOrThrow({ where: { slug: body.sportSlug } }); await prisma.checkIn.updateMany({ where: { userId: req.user!.id, endedAt: null }, data: { endedAt: new Date() } }); const checkIn = await prisma.checkIn.create({ data: { userId: req.user!.id, venueId: body.venueId, sportId: sport.id, expiresAt: new Date(Date.now() + 120 * 60_000), headcount: body.headcount, gameType: body.gameType, skillLevel: body.skillLevel, note: body.note }, include: { user: true, venue: true, sport: true } }); await prisma.activity.create({ data: { actorId: req.user!.id, type: 'CHECKED_IN', venueId: body.venueId, sportId: sport.id, checkInId: checkIn.id, payload: {} } }); res.status(201).json({ checkIn }); }));
router.get('/check-ins/active', requireAuth, asyncHandler(async (req, res) => res.json({ checkIn: await prisma.checkIn.findFirst({ where: { userId: req.user!.id, endedAt: null, expiresAt: { gt: new Date() } }, include: { user: true, venue: true, sport: true }, orderBy: { startedAt: 'desc' } }) })));
router.get('/check-ins/nearby', optionalAuth, asyncHandler(async (_req, res) => { const rows = await prisma.checkIn.findMany({ where: { endedAt: null, expiresAt: { gt: new Date() } }, include: { venue: true, sport: true }, take: 50 }); res.json({ items: rows }); }));
router.patch('/check-ins/:id', requireAuth, asyncHandler(async (req, res) => { const item = await prisma.checkIn.findUnique({ where: { id: routeParam(req.params.id) } }); if (!item) throw notFound(); if (item.userId !== req.user!.id) throw forbidden(); res.json({ checkIn: await prisma.checkIn.update({ where: { id: item.id }, data: req.body }) }); }));
router.post('/check-ins/:id/end', requireAuth, asyncHandler(async (req, res) => { const item = await prisma.checkIn.findUnique({ where: { id: routeParam(req.params.id) } }); if (!item) throw notFound(); if (item.userId !== req.user!.id) throw forbidden(); res.json({ checkIn: await prisma.checkIn.update({ where: { id: item.id }, data: { endedAt: new Date() } }) }); }));

router.post('/follows', requireAuth, validate({ body: FollowBody }), asyncHandler(async (req, res) => { const userId = (req.body as { userId: string }).userId; if (userId === req.user!.id) throw conflict('You cannot follow yourself.'); await prisma.follow.upsert({ where: { followerId_followeeId: { followerId: req.user!.id, followeeId: userId } }, create: { followerId: req.user!.id, followeeId: userId }, update: {} }); res.status(204).end(); }));
router.delete('/follows/:userId', requireAuth, asyncHandler(async (req, res) => { await prisma.follow.deleteMany({ where: { followerId: req.user!.id, followeeId: routeParam(req.params.userId) } }); res.status(204).end(); }));
router.get('/users/search', optionalAuth, asyncHandler(async (req, res) => { const q = String(req.query.q ?? ''); const users = await prisma.user.findMany({ where: { OR: [{ handle: { contains: q, mode: 'insensitive' } }, { displayName: { contains: q, mode: 'insensitive' } }] }, take: 10 }); res.json({ items: users.map(mini) }); }));
router.get('/users/:handle/affinity', requireAuth, asyncHandler(async (req, res) => {
  const peer = await prisma.user.findUnique({ where: { handle: routeParam(req.params.handle) } });
  if (!peer) throw notFound();
  const [affinities, entries] = await Promise.all([
    prisma.tasteAffinity.findMany({ where: { userAId: req.user!.id, userBId: peer.id }, include: { sport: true } }),
    prisma.entry.findMany({ where: { userId: { in: [req.user!.id, peer.id] }, status: 'RANKED', rankPosition: { not: null } }, include: { venue: true, sport: true } }),
  ]);
  const mine = new Map(entries.filter((entry) => entry.userId === req.user!.id).map((entry) => [`${entry.sportId}:${entry.venueId}`, entry]));
  const theirs = entries.filter((entry) => entry.userId === peer.id);
  const points = theirs.flatMap((entry) => { const own = mine.get(`${entry.sportId}:${entry.venueId}`); return own?.rankPosition && entry.rankPosition ? [{ venue: { id: entry.venue.id, slug: entry.venue.slug, name: entry.venue.name, neighborhood: entry.venue.neighborhood, city: entry.venue.city, photoUrl: entry.venue.photoUrl }, mineRank: own.rankPosition, theirRank: entry.rankPosition }] : []; });
  const aggregateTau = affinities.length ? affinities.reduce((sum, item) => sum + Number(item.tau) * item.overlapN, 0) / affinities.reduce((sum, item) => sum + item.overlapN, 0) : 0;
  res.json({ affinity: { tau: aggregateTau, overlapN: points.length, points } });
}));
router.get('/users/:handle', optionalAuth, asyncHandler(async (req, res) => { const user = await prisma.user.findUnique({ where: { handle: routeParam(req.params.handle) } }); if (!user) throw notFound(); const sports = await prisma.userSport.findMany({ where: { userId: user.id }, include: { sport: true } }); const followerCount = await prisma.follow.count({ where: { followeeId: user.id } }); const followingCount = await prisma.follow.count({ where: { followerId: user.id } }); const isFollowing = req.user ? Boolean(await prisma.follow.findUnique({ where: { followerId_followeeId: { followerId: req.user.id, followeeId: user.id } } })) : false; res.json({ user: { ...mini(user), bio: user.bio, homeCity: user.homeCity, homeLat: user.homeLat, homeLng: user.homeLng, isDemo: user.isDemo, createdAt: user.createdAt.toISOString(), sports: sports.map((x) => ({ slug: x.sport.slug, name: x.sport.name, skillLevel: x.skillLevel, isPrimary: x.isPrimary })), followerCount, followingCount, isFollowing } }); }));
router.get('/users/:handle/:kind(followers|following)', optionalAuth, asyncHandler(async (req, res) => { const user = await prisma.user.findUnique({ where: { handle: routeParam(req.params.handle) } }); if (!user) throw notFound(); const following = req.params.kind === 'following'; const follows = await prisma.follow.findMany({ where: following ? { followerId: user.id } : { followeeId: user.id }, include: { followee: true, follower: true }, take: 50 }); res.json({ items: follows.map((item) => mini(following ? item.followee : item.follower)), nextCursor: null }); }));
router.get('/feed/social', requireAuth, asyncHandler(async (req, res) => { const follows = await prisma.follow.findMany({ where: { followerId: req.user!.id }, select: { followeeId: true } }); const rows = await prisma.activity.findMany({ where: { actorId: { in: [req.user!.id, ...follows.map((x) => x.followeeId)] } }, include: { actor: true, venue: true, sport: true, entry: { include: { venue: true } }, checkIn: { include: { venue: true, sport: true, user: true } } }, orderBy: { createdAt: 'desc' }, take: 30 }); res.json({ items: rows, nextCursor: null }); }));
router.post('/want-to-try', requireAuth, validate({ body: WantToTryBody }), asyncHandler(async (req, res) => { const body = req.body as typeof WantToTryBody._output; const sport = await prisma.sport.findUniqueOrThrow({ where: { slug: body.sportSlug } }); res.status(201).json({ wantToTry: await prisma.wantToTry.upsert({ where: { userId_venueId_sportId: { userId: req.user!.id, venueId: body.venueId, sportId: sport.id } }, create: { userId: req.user!.id, venueId: body.venueId, sportId: sport.id, source: body.source }, update: {} }) }); }));
router.delete('/want-to-try/:venueId', requireAuth, asyncHandler(async (req, res) => { const sport = await prisma.sport.findUniqueOrThrow({ where: { slug: String(req.query.sport) as never } }); await prisma.wantToTry.deleteMany({ where: { userId: req.user!.id, venueId: routeParam(req.params.venueId), sportId: sport.id } }); res.status(204).end(); }));
router.get('/me/want-to-try', requireAuth, asyncHandler(async (req, res) => res.json({ items: await prisma.wantToTry.findMany({ where: { userId: req.user!.id }, include: { venue: true, sport: true } }), nextCursor: null })));

export default router;
