import { Router, type Router as RouterType } from 'express';
import { prisma } from '@rally/db';
import { requireAuth, optionalAuth } from '../middleware/auth.js';
import { asyncHandler, notFound } from '../middleware/error.js';

const router: RouterType = Router();
const param = (value: string | string[]) => Array.isArray(value) ? value[0] : value;

function card(venue: { id: string; slug: string; name: string; neighborhood: string | null; city: string; lat: number; lng: number; photoUrl: string | null; isIndoor: boolean; isFree: boolean; hasLights: boolean; requiresReservation: boolean; venueSports: { courtCount: number; surface: string | null; sport: { slug: string; name: string; colorHex: string } }[]; venueSportRatings: { elo: unknown }[]; checkIns: { headcount: number; gameType: string; skillLevel: string; startedAt: Date }[] }, lat?: number, lng?: number) {
  const distanceMeters = lat === undefined || lng === undefined ? null : Math.round(Math.hypot((venue.lat - lat) * 111_000, (venue.lng - lng) * 83_000));
  const live = venue.checkIns[0]; const rating = venue.venueSportRatings[0]; const score = Math.max(0, Math.min(10, 5 + (Number(rating?.elo ?? 1500) - 1500) / 100));
  return { id: venue.id, slug: venue.slug, name: venue.name, neighborhood: venue.neighborhood, city: venue.city, lat: venue.lat, lng: venue.lng, photoUrl: venue.photoUrl, distanceMeters, sports: venue.venueSports.map((x) => ({ slug: x.sport.slug, name: x.sport.name, colorHex: x.sport.colorHex, courtCount: x.courtCount, surface: x.surface })), isIndoor: venue.isIndoor, isFree: venue.isFree, hasLights: venue.hasLights, requiresReservation: venue.requiresReservation, live: live ? { activeCount: venue.checkIns.length, headcount: Math.max(...venue.checkIns.map((x) => x.headcount)), gameType: live.gameType, skillLevel: live.skillLevel, lastCheckInAt: live.startedAt.toISOString() } : null, myEntry: null, inWantToTry: false, cityElo: Number(rating?.elo ?? 1500), reco: { rallyScore: Number(score.toFixed(1)), components: { personal: null, social: null, proximity: distanceMeters === null ? null : Math.exp(-distanceMeters / 3000), live: live ? 0.8 : null, gate: 1 }, gateReason: null, why: live ? [`${Math.max(...venue.checkIns.map((x) => x.headcount))} here now · ${live.gameType.toLowerCase()}`] : distanceMeters === null ? ['Popular in Chicago'] : [`${(distanceMeters / 1609).toFixed(1)} mi away`] } };
}

const include = { venueSports: { include: { sport: true } }, venueSportRatings: true, checkIns: { where: { endedAt: null, expiresAt: { gt: new Date() } }, orderBy: { startedAt: 'desc' as const } } };
router.get('/sports', asyncHandler(async (_req, res) => res.set('Cache-Control', 'public, max-age=3600').json({ items: await prisma.sport.findMany({ orderBy: { name: 'asc' } }) })));
router.get('/feed/recommended', requireAuth, asyncHandler(async (req, res) => { const sport = typeof req.query.sport === 'string' ? req.query.sport : undefined; const lat = Number(req.query.lat); const lng = Number(req.query.lng); const venues = await prisma.venue.findMany({ where: sport ? { venueSports: { some: { sport: { slug: sport as never } } } } : undefined, include, take: 50 }); const items = venues.map((venue) => card(venue, Number.isFinite(lat) ? lat : undefined, Number.isFinite(lng) ? lng : undefined)).filter((item) => !Boolean(req.query.playableNow === 'true') || item.live !== null).sort((a, b) => (b.reco?.rallyScore ?? 0) - (a.reco?.rallyScore ?? 0)); res.json({ items, weights: { personal: .35, social: .25, proximity: .2, live: .2 } }); }));
router.get('/venues', optionalAuth, asyncHandler(async (req, res) => { const venues = await prisma.venue.findMany({ include, take: Math.min(Number(req.query.limit ?? 20), 50) }); const lat = Number(req.query.lat); const lng = Number(req.query.lng); res.json({ items: venues.map((venue) => card(venue, Number.isFinite(lat) ? lat : undefined, Number.isFinite(lng) ? lng : undefined)), nextCursor: null }); }));
router.get('/venues/:id', optionalAuth, asyncHandler(async (req, res) => { const venue = await prisma.venue.findUnique({ where: { id: param(req.params.id) }, include: { ...include, reviews: { include: { user: true, sport: true } }, checkIns: { include: { user: true, sport: true, venue: true }, where: { endedAt: null, expiresAt: { gt: new Date() } } } } }); if (!venue) throw notFound(); res.json({ venue: { ...card({ ...venue, checkIns: venue.checkIns }, undefined, undefined), address: venue.address, state: venue.state, country: venue.country, hasParking: venue.hasParking, hasRestrooms: venue.hasRestrooms, hasWater: venue.hasWater, source: venue.source, conditionNotes: null, reviews: venue.reviews, checkIns: venue.checkIns } }); }));
router.get('/venues/:id/live', optionalAuth, asyncHandler(async (req, res) => { const rows = await prisma.checkIn.findMany({ where: { venueId: param(req.params.id), endedAt: null, expiresAt: { gt: new Date() } }, orderBy: { startedAt: 'desc' } }); res.json(rows.length ? { activeCount: rows.length, headcount: Math.max(...rows.map((x) => x.headcount)), gameType: rows[0].gameType, skillLevel: rows[0].skillLevel, lastCheckInAt: rows[0].startedAt.toISOString() } : null); }));
router.get('/leaderboard', optionalAuth, asyncHandler(async (req, res) => { const sport = String(req.query.sport ?? 'basketball'); const ratings = await prisma.venueSportRating.findMany({ where: { sport: { slug: sport as never } }, include: { venue: true, sport: true }, orderBy: [{ elo: 'desc' }, { nEntries: 'desc' }], take: Number(req.query.limit ?? 30) }); res.json({ items: ratings.map((rating, index) => ({ rank: index + 1, venue: { id: rating.venue.id, slug: rating.venue.slug, name: rating.venue.name, neighborhood: rating.venue.neighborhood, city: rating.venue.city, photoUrl: rating.venue.photoUrl }, sportSlug: rating.sport.slug, elo: Number(rating.elo), confidenceScore: rating.nComparisons / (rating.nComparisons + 8), nComparisons: rating.nComparisons, avgRallyScore: rating.avgRallyScore === null ? null : Number(rating.avgRallyScore), nEntries: rating.nEntries, movement: null })), nextCursor: null }); }));

export default router;
