'use client';

import { useState } from 'react';
import { useQuery, useQueryClient } from '@tanstack/react-query';
import { ArrowLeft, Check, Heart, MapPin, Share2, Users } from 'lucide-react';
import Link from 'next/link';
import { useRouter } from 'next/navigation';
import type { GameType, SkillLevel, VenueDetail } from '@rally/shared';
import { api } from '@/lib/api-client';
import { LiveBadge } from '@/components/venue/live-badge';
import { ScoreBadge } from '@/components/venue/score-badge';
import { SportChip } from '@/components/venue/sport-chip';
import { EmptyState } from '@/components/shared/empty-state';
import { VenuePhoto } from '@/components/venue/venue-photo';

const gameTypes: GameType[] = ['PICKUP', 'CASUAL', 'COMPETITIVE', 'DRILLS', 'LEAGUE', 'SOLO'];
const skills: SkillLevel[] = ['BEGINNER', 'INTERMEDIATE', 'ADVANCED', 'ANY'];

export function VenueDetailClient({ initialVenue }: { initialVenue: VenueDetail }) {
  const client = useQueryClient(); const router = useRouter(); const [dialog, setDialog] = useState(false); const [wanted, setWanted] = useState(initialVenue.inWantToTry); const [checkedIn, setCheckedIn] = useState(false);
  const live = useQuery({ queryKey: ['venue-live', initialVenue.id], queryFn: () => api.get<typeof initialVenue.live>(`/venues/${initialVenue.id}/live`), initialData: initialVenue.live, refetchInterval: 45_000, refetchOnWindowFocus: true });
  const status = live.data ?? initialVenue.live;
  const copy = async () => { await navigator.clipboard.writeText(window.location.href); };
  const checkIn = async (payload: { headcount: number; gameType: GameType; skillLevel: SkillLevel; note: string }) => { setCheckedIn(true); setDialog(false); await api.post('/check-ins', { venueId: initialVenue.id, sportSlug: initialVenue.sports[0]?.slug, ...payload }).catch(() => undefined); await client.invalidateQueries({ queryKey: ['venue-live', initialVenue.id] }); await client.invalidateQueries({ queryKey: ['recommended'] }); };
  return <main className="mx-auto min-h-dvh max-w-3xl bg-rally-base pb-24"><VenueHero venue={initialVenue} /><div className="space-y-7 px-4 py-5"><Playability venue={initialVenue} /><LivePanel live={status} onCheckIn={() => setDialog(true)} /><ScoreTriad venue={initialVenue} /><Conditions venue={initialVenue} /><FriendRankings /><Reviews /></div><ActionBar wanted={wanted} setWanted={setWanted} checkedIn={checkedIn} onCheckIn={() => setDialog(true)} onShare={copy} onLog={() => router.push(`/log/${initialVenue.id}`)} />{dialog ? <CheckInDialog venue={initialVenue} close={() => setDialog(false)} submit={checkIn} /> : null}</main>;
}
function VenueHero({ venue }: { venue: VenueDetail }) { return <header className="relative min-h-64 overflow-hidden border-b border-rally-border bg-rally-elevated p-4"><VenuePhoto src={venue.photoUrl} alt={`${venue.name} court`} priority sizes="(max-width: 1024px) 100vw, 768px" className="object-cover opacity-45" /><div className="absolute inset-0 bg-gradient-to-t from-rally-base via-rally-base/40 to-transparent" /><Link href="/" aria-label="Back to nearby venues" className="relative grid size-11 place-items-center rounded-full border border-rally-border bg-rally-base/90"><ArrowLeft size={18} /></Link><div className="absolute inset-x-4 bottom-5"><p className="mb-2 flex items-center gap-1 text-sm text-rally-secondary"><MapPin size={14} />{venue.neighborhood ?? venue.city} · {venue.distanceMeters ? `${(venue.distanceMeters / 1609).toFixed(1)} mi` : venue.city}</p><h1 className="text-3xl font-semibold tracking-tight">{venue.name}</h1><div className="mt-3 flex flex-wrap gap-2">{venue.sports.map((sport) => <SportChip key={sport.slug} name={sport.name} color={sport.colorHex} />)}</div></div></header>; }
function Playability({ venue }: { venue: VenueDetail }) { const gated = venue.reco?.components.gate !== 1; const reason = venue.reco?.gateReason; if (!reason && venue.isIndoor) return null; return <section className={`rounded-card border p-4 ${gated ? 'border-amber-500/50 bg-amber-500/10' : 'border-emerald-500/35 bg-emerald-500/10'}`}><p className="font-medium">{reason ?? 'Good conditions · outdoor court'}</p><p className="mt-1 text-sm text-rally-secondary">{gated ? 'Conditions may affect play right now.' : 'Check in to let others know the court is on.'}</p></section>; }
function LivePanel({ live, onCheckIn }: { live: VenueDetail['live']; onCheckIn: () => void }) { return <section className="rounded-card border border-rally-border bg-rally-surface p-5"><div className="flex items-start justify-between"><div><p className="text-sm text-rally-secondary">LIVE AT THIS VENUE</p><p className="mt-1 text-4xl font-semibold tabular-nums">{live?.headcount ?? 0} <span className="text-lg text-rally-secondary">here now</span></p></div>{live?.activeCount ? <LiveBadge count={live.headcount} gameType={live.gameType} /> : null}</div>{live ? <p className="mt-4 text-sm text-rally-secondary">Updated just now · {live.skillLevel?.toLowerCase() ?? 'all levels'} welcome</p> : <div className="mt-4 flex items-center justify-between gap-3"><p className="text-sm text-rally-secondary">No one checked in right now · Be the first</p><button onClick={onCheckIn} className="min-h-11 rounded-control bg-emerald-400 px-4 text-sm font-semibold text-black">Check in</button></div>}</section>; }
function ScoreTriad({ venue }: { venue: VenueDetail }) { return <section className="grid grid-cols-3 divide-x divide-rally-border rounded-card border border-rally-border bg-rally-surface text-center"><Metric label="YOUR SCORE" value={venue.myEntry ? venue.myEntry.rallyScore.toFixed(1) : '—'} /><Metric label="FRIENDS" value="—" /><Metric label="CITY" value={venue.myEntry ? `#${venue.myEntry.rankPosition}` : '—'} /></section>; }
function Metric({ label, value }: { label: string; value: string }) { return <div className="p-4"><p className="text-xs text-rally-secondary">{label}</p><p className="mt-1 text-2xl font-semibold tabular-nums">{value}</p></div>; }
function Conditions({ venue }: { venue: VenueDetail }) { const primary = venue.sports[0]; const values = [['Surface', primary?.surface ?? '—'], ['Lights', venue.hasLights ? 'Yes' : '—'], ['Indoor', venue.isIndoor ? 'Yes' : 'No'], ['Free', venue.isFree ? 'Yes' : '—'], ['Parking', venue.hasParking ? 'Yes' : '—'], ['Water', venue.hasWater ? 'Yes' : '—']]; return <section><h2 className="mb-3 text-lg font-semibold">Conditions</h2><div className="grid grid-cols-3 gap-2">{values.map(([label, value]) => <div key={label} className="rounded-control border border-rally-border bg-rally-surface p-3"><p className="text-xs text-rally-secondary">{label}</p><p className="mt-1 text-sm">{value}</p></div>)}</div></section>; }
function FriendRankings() { return <section><h2 className="mb-3 text-lg font-semibold">Friends&apos; rankings</h2><EmptyState icon={<Users size={22} />} headline="No friend rankings yet" body="Follow players with similar taste to see their takes here." /></section>; }
function Reviews() { return <section><h2 className="mb-3 text-lg font-semibold">Reviews</h2><EmptyState icon="✦" headline="No reviews yet" body="Be the first to share a useful court note." /></section>; }
function ActionBar({ wanted, setWanted, checkedIn, onCheckIn, onShare, onLog }: { wanted: boolean; setWanted: (value: boolean) => void; checkedIn: boolean; onCheckIn: () => void; onShare: () => void; onLog: () => void }) { return <div className="fixed inset-x-0 bottom-0 z-30 mx-auto flex max-w-3xl gap-2 border-t border-rally-border bg-rally-base/95 p-3 backdrop-blur"><button onClick={onLog} className="min-h-11 flex-1 rounded-control bg-emerald-400 px-4 font-semibold text-black">Log a visit</button><button onClick={onCheckIn} className="min-h-11 rounded-control border border-rally-border px-4 text-sm">{checkedIn ? <Check size={17} /> : 'Check in'}</button><button onClick={() => setWanted(!wanted)} aria-label="Want to try" className={`grid size-11 place-items-center rounded-control border border-rally-border ${wanted ? 'text-rose-400' : ''}`}><Heart size={18} fill={wanted ? 'currentColor' : 'none'} /></button><button onClick={onShare} aria-label="Share venue" className="grid size-11 place-items-center rounded-control border border-rally-border"><Share2 size={17} /></button></div>; }
function CheckInDialog({ venue, close, submit }: { venue: VenueDetail; close: () => void; submit: (payload: { headcount: number; gameType: GameType; skillLevel: SkillLevel; note: string }) => void }) { const [count, setCount] = useState(8); const [gameType, setGameType] = useState<GameType>('PICKUP'); const [skillLevel, setSkillLevel] = useState<SkillLevel>('INTERMEDIATE'); const [note, setNote] = useState(''); return <div role="dialog" aria-modal="true" className="fixed inset-0 z-50 grid place-items-end bg-black/60 p-3 sm:place-items-center"><form onSubmit={(event) => { event.preventDefault(); submit({ headcount: count, gameType, skillLevel, note }); }} className="w-full max-w-md rounded-card border border-rally-border bg-rally-surface p-5"><h2 className="text-xl font-semibold">Check in at {venue.name}</h2><label className="mt-5 block text-sm">People here <span className="float-right tabular-nums">{count}</span><input className="mt-2 w-full accent-emerald-400" type="range" min="1" max="30" value={count} onChange={(event) => setCount(Number(event.target.value))} /></label><Choice label="Game type" values={gameTypes} selected={gameType} setSelected={setGameType} /><Choice label="Skill level" values={skills} selected={skillLevel} setSelected={setSkillLevel} /><label className="mt-4 block text-sm">Note <textarea maxLength={80} value={note} onChange={(event) => setNote(event.target.value)} placeholder="full court running, need 2" className="mt-2 w-full rounded-control border border-rally-border bg-rally-base p-3" /></label><div className="mt-5 flex justify-end gap-2"><button type="button" onClick={close} className="min-h-11 px-3 text-sm">Cancel</button><button className="min-h-11 rounded-control bg-emerald-400 px-4 text-sm font-semibold text-black">Check in</button></div></form></div>; }
function Choice<T extends string>({ label, values, selected, setSelected }: { label: string; values: T[]; selected: T; setSelected: (value: T) => void }) { return <fieldset className="mt-4"><legend className="text-sm">{label}</legend><div className="mt-2 flex flex-wrap gap-2">{values.map((value) => <button type="button" key={value} onClick={() => setSelected(value)} className={`min-h-10 rounded-control border px-3 text-xs ${selected === value ? 'border-emerald-400 bg-emerald-400/15' : 'border-rally-border'}`}>{value.toLowerCase()}</button>)}</div></fieldset>; }
