import { readFile } from 'node:fs/promises';
import { join } from 'node:path';
import { prisma, setVenueGeom } from '@rally/db';
import { IDEAL_COUNT, type GameType, type SkillLevel, type SportSlug } from '@rally/shared';
import { createEntryAndSession, submitComparison } from '../apps/api/src/services/ranking/service.js';
import { recomputeAffinityFor } from '../apps/api/src/services/ranking/affinity.js';

type SeedVenue = { osmId: string; name: string; slug: string; lat: number; lng: number; neighborhood: string | null; address: string | null; isIndoor: boolean; isFree: boolean; requiresReservation: boolean; hasLights: boolean; hasParking: boolean; hasRestrooms: boolean; hasWater: boolean; photoUrl: string; sports: { slug: SportSlug; courtCount: number; surface: never; isLit: boolean | null }[] };
type Person = { handle: string; name: string; sports: SportSlug[]; skill: SkillLevel; lat: number; lng: number };
const seed = 20260721; let state = seed;
const random = () => { state |= 0; state = state + 0x6d2b79f5 | 0; let value = Math.imul(state ^ state >>> 15, 1 | state); value ^= value + Math.imul(value ^ value >>> 7, 61 | value); return ((value ^ value >>> 14) >>> 0) / 4294967296; };
const pick = <T>(items: T[]) => items[Math.floor(random() * items.length)];
const shuffle = <T>(items: T[]) => { const output = [...items]; for (let index = output.length - 1; index > 0; index -= 1) { const other = Math.floor(random() * (index + 1)); [output[index], output[other]] = [output[other], output[index]]; } return output; };
const distance = (a: { lat: number; lng: number }, b: { lat: number; lng: number }) => Math.hypot(a.lat - b.lat, a.lng - b.lng) * 111;
const sports: { slug: SportSlug; name: string; iconKey: string; colorHex: string; outdoor: boolean }[] = [
  ['basketball','Basketball','CircleDot','#F97316',true],['pickleball','Pickleball','Trophy','#A3E635',true],['tennis','Tennis','CircleDot','#84CC16',true],['soccer','Soccer','Goal','#38BDF8',true],['volleyball','Volleyball','CircleDot','#A78BFA',true],['baseball','Baseball','CircleDot','#F472B6',true],['softball','Softball','CircleDot','#FB7185',true],['running_track','Running Track','Route','#22D3EE',true],['golf_range','Golf Range','Flag','#34D399',true],['skate','Skate','Zap','#FBBF24',true],['football','Football','Trophy','#60A5FA',true],['handball','Handball','CircleDot','#F87171',true],
].map(([slug,name,iconKey,colorHex,outdoor]) => ({ slug: slug as SportSlug, name, iconKey, colorHex, outdoor }));
const homes = [[41.918,-87.652],[41.949,-87.675],[41.878,-87.630],[41.968,-87.688],[41.790,-87.600],[41.900,-87.720],[41.820,-87.680],[41.999,-87.660],[41.740,-87.610],[41.920,-87.700],[41.860,-87.650],[41.940,-87.640]];
const people: Person[] = [
  { handle: 'marcus', name: 'Marcus Reed', sports: ['basketball','football'], skill: 'ADVANCED', ...toHome(0) }, { handle: 'priya', name: 'Priya Shah', sports: ['pickleball','tennis'], skill: 'INTERMEDIATE', ...toHome(1) },
  ...Array.from({ length: 16 }, (_, index) => { const profiles: [SportSlug[], SkillLevel][] = [[['basketball'],'ADVANCED'],[['basketball'],'INTERMEDIATE'],[['pickleball','tennis'],'INTERMEDIATE'],[['tennis'],'ADVANCED'],[['soccer'],'ADVANCED'],[['basketball','soccer','volleyball'],'ANY']]; const [userSports, skill] = profiles[index % profiles.length]; return { handle: `rally${index + 1}`, name: ['Jordan Kim','Avery Clark','Noah Patel','Sofia Rivera','Theo Martin','Maya Chen'][index % 6], sports: userSports, skill, ...toHome(index % homes.length) }; }),
];
function toHome(index: number) { const [lat, lng] = homes[index]; return { lat, lng }; }
async function adminUser(person: Person) {
  const password = process.env.DEMO_PASSWORD; const url = process.env.NEXT_PUBLIC_SUPABASE_URL; const key = process.env.SUPABASE_SERVICE_ROLE_KEY;
  if (!password || !url || !key) throw new Error('DEMO_PASSWORD, NEXT_PUBLIC_SUPABASE_URL, and SUPABASE_SERVICE_ROLE_KEY are required.');
  const email = `${person.handle}@rally.demo`; const response = await fetch(`${url}/auth/v1/admin/users`, { method: 'POST', headers: { apikey: key, Authorization: `Bearer ${key}`, 'content-type': 'application/json' }, body: JSON.stringify({ email, password, email_confirm: true }) });
  const json = await response.json() as { id?: string; msg?: string }; if (!response.ok && !json.msg?.includes('already')) throw new Error(json.msg ?? 'Could not create auth user.');
  if (json.id) return json.id; const existing = await fetch(`${url}/auth/v1/admin/users?email=${encodeURIComponent(email)}`, { headers: { apikey: key, Authorization: `Bearer ${key}` } }); const list = await existing.json() as { users?: { id: string }[] }; const id = list.users?.[0]?.id; if (!id) throw new Error(`Could not resolve ${email}.`); return id;
}
async function seedVenues() {
  const venues = JSON.parse(await readFile(join(process.cwd(), 'scripts/data/chicago-venues.normalized.json'), 'utf8')) as SeedVenue[]; const quality = new Map<string, number>();
  for (const venue of venues) { const record = await prisma.venue.upsert({ where: { osmId: venue.osmId }, create: { osmId: venue.osmId, name: venue.name, slug: venue.slug, lat: venue.lat, lng: venue.lng, neighborhood: venue.neighborhood, address: venue.address, isIndoor: venue.isIndoor, isFree: venue.isFree, requiresReservation: venue.requiresReservation, hasLights: venue.hasLights, hasParking: venue.hasParking, hasRestrooms: venue.hasRestrooms, hasWater: venue.hasWater, photoUrl: venue.photoUrl }, update: { name: venue.name, slug: venue.slug } }); await setVenueGeom(prisma, record.id, venue.lat, venue.lng); quality.set(record.id, (random() + random() + random() + random() + random()) / 5); for (const item of venue.sports) { const sport = await prisma.sport.findUniqueOrThrow({ where: { slug: item.slug } }); await prisma.venueSport.upsert({ where: { venueId_sportId: { venueId: record.id, sportId: sport.id } }, create: { venueId: record.id, sportId: sport.id, courtCount: item.courtCount, surface: item.surface, isLit: item.isLit }, update: {} }); await prisma.venueSportRating.upsert({ where: { venueId_sportId: { venueId: record.id, sportId: sport.id } }, create: { venueId: record.id, sportId: sport.id }, update: {} }); } }
  return quality;
}
async function rankUser(person: Person, id: string, quality: Map<string, number>) { const available = await prisma.venue.findMany({ where: { venueSports: { some: { sport: { slug: { in: person.sports } } } } }, include: { venueSports: { include: { sport: true } } } }); const picks = available.sort((a,b) => Math.exp(-distance(person,a)/4) - Math.exp(-distance(person,b)/4)).slice(-Math.min(10, available.length)); const scores = new Map(picks.map((venue) => [venue.id, (quality.get(venue.id) ?? .5) + random() * .2])); for (const venue of shuffle(picks)) { const sport = venue.venueSports.find((item) => person.sports.includes(item.sport.slug))!.sport.slug; const ordered = [...scores.entries()].sort((a,b) => b[1]-a[1]); const position = ordered.findIndex(([venueId]) => venueId === venue.id); const sentiment = position < Math.ceil(ordered.length*.45) ? 'LIKED' : position < Math.ceil(ordered.length*.85) ? 'FINE' : 'DISLIKED'; const created = await createEntryAndSession(id, venue.id, sport, sentiment, { tags: [], playedAt: new Date() }); let session = created.session; while (session.status === 'ACTIVE') { const band = await prisma.entry.findMany({ where: { userId: id, sport: { slug }, sentiment, status: 'RANKED' }, orderBy: { rankPosition: 'asc' } }); const mid = Math.floor((session.lo + session.hi)/2); const opponent = band[mid]; const answer = opponent && (scores.get(venue.id)! > (scores.get(opponent.venueId) ?? .5)) ? created.entry.id : opponent?.id ?? created.entry.id; const next = await submitComparison(id, session.id, random() < .05 ? null : answer); if ('result' in next) break; session = await prisma.comparisonSession.findUniqueOrThrow({ where: { id: session.id } }); } } }
export async function refreshLiveCheckIns(): Promise<void> { await prisma.checkIn.updateMany({ where: { endedAt: null }, data: { endedAt: new Date() } }); const demos = await prisma.user.findMany({ where: { handle: { in: ['marcus','priya'] } }, include: { userSports: { include: { sport: true } } } }); for (let index=0; index<10; index+=1) { const user = demos[index%demos.length]; const sport = pick(user.userSports).sport; const venue = await prisma.venue.findFirstOrThrow({ where: { venueSports: { some: { sportId: sport.id } } } }); const startedAt = new Date(Date.now()-(5+Math.floor(random()*70))*60_000); await prisma.checkIn.create({ data: { userId: user.id, venueId: venue.id, sportId: sport.id, startedAt, expiresAt: new Date(startedAt.getTime()+120*60_000), headcount: Math.max(1, IDEAL_COUNT[sport.slug]+Math.floor(random()*5)-2), gameType: 'PICKUP' as GameType, skillLevel: user.userSports[0].skillLevel } }); console.log(`${venue.name}: ${IDEAL_COUNT[sport.slug]} players`); } }
async function main() { if (process.argv.includes('--live-only')) return refreshLiveCheckIns(); for (const sport of sports) await prisma.sport.upsert({ where: { slug: sport.slug }, create: { slug: sport.slug, name: sport.name, iconKey: sport.iconKey, colorHex: sport.colorHex, defaultIsOutdoor: sport.outdoor }, update: sport }); const quality = await seedVenues(); const ids = new Map<string,string>(); for (const person of people) { const id = await adminUser(person); ids.set(person.handle,id); await prisma.user.upsert({ where: { id }, create: { id, handle: person.handle, displayName: person.name, avatarUrl: `https://api.dicebear.com/9.x/initials/svg?seed=${person.handle}`, homeLat: person.lat, homeLng: person.lng, isDemo: true }, update: { handle: person.handle, displayName: person.name, isDemo: true } }); for (const slug of person.sports) { const sport = await prisma.sport.findUniqueOrThrow({where:{slug}}); await prisma.userSport.upsert({where:{userId_sportId:{userId:id,sportId:sport.id}},create:{userId:id,sportId:sport.id,skillLevel:person.skill,preferredGameTypes:['PICKUP'],isPrimary:slug===person.sports[0]},update:{}}); } await rankUser(person,id,quality); } await refreshLiveCheckIns(); for (const [handle,id] of ids) for (const slug of people.find((person)=>person.handle===handle)!.sports) await recomputeAffinityFor(id,slug); console.log(await prisma.$transaction([prisma.user.count(),prisma.venue.count(),prisma.entry.count(),prisma.comparison.count(),prisma.checkIn.count()])); }
void main().finally(() => prisma.$disconnect());
